name: My Main Workflow

on:
  pull_request:

jobs:
  main-job:
    name: My Main Job
    runs-on: ubuntu-latest
    outputs:
      YOLO: ${{ steps.yolo-id.outputs.YOLO }}
    steps:
      - uses: actions/checkout@v3

      - run: echo "Hello World"

      - run: cat README.md

      - run: echo "YOLO=SWAG" >> $GITHUB_OUTPUT
        id: yolo-id

      - run: echo "$YOLO"

      - run: echo "$YOLO"
        env:
          YOLO: ${{ steps.yolo-id.outputs.YOLO }}

  second-job:
    name: My Awesome Second Job
    runs-on: ubuntu-latest
    needs: main-job
    steps:
      - run: echo $YOLO
        env:
          YOLO: ${{ needs.main-job.outputs.YOLO }}
