name: My Main Workflow

on:
  pull_request:

jobs:
  main-job:
    name: My Main Job
    runs-on: ubuntu-latest
    outputs:
      YOLO: ${{ steps.yolo-id.outputs.YOLO }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/say-hello

      - run: echo "Hello World"

      - run: cat README.md >> $GITHUB_SUMMARY

      - run: echo "YOLO=SWAG" >> $GITHUB_OUTPUT
        id: yolo-id

      - run: echo "$YOLO" # undefined!

      - run: echo "$YOLO"
        env:
          YOLO: ${{ steps.yolo-id.outputs.YOLO }} # set $YOLO from outputs

  second-job:
    name: My Awesome Second Job
    runs-on: ubuntu-latest
    needs:
      - main-job
    steps:
      - run: echo $YOLO
        env:
          YOLO: ${{ needs.main-job.outputs.YOLO }}
